"C:\Program Files\Sublime Text 3\sublime_text.exe" .gitignore
"C:\Program Files\Sublime Text 3\sublime_text.exe" Packages/manifest.json
"C:\Program Files\Sublime Text 3\sublime_text.exe" ProjectSettings/AudioManager.asset
"C:\Program Files\Sublime Text 3\sublime_text.exe" ProjectSettings/DynamicsManager.asset
"C:\Program Files\Sublime Text 3\sublime_text.exe" ProjectSettings/EditorBuildSettings.asset
"C:\Program Files\Sublime Text 3\sublime_text.exe" ProjectSettings/EditorSettings.asset
"C:\Program Files\Sublime Text 3\sublime_text.exe" ProjectSettings/GraphicsSettings.asset
"C:\Program Files\Sublime Text 3\sublime_text.exe" ProjectSettings/InputManager.asset
"C:\Program Files\Sublime Text 3\sublime_text.exe" ProjectSettings/NavMeshAreas.asset
"C:\Program Files\Sublime Text 3\sublime_text.exe" ProjectSettings/Physics2DSettings.asset
"C:\Program Files\Sublime Text 3\sublime_text.exe" ProjectSettings/ProjectSettings.asset
"C:\Program Files\Sublime Text 3\sublime_text.exe" ProjectSettings/ProjectVersion.txt
"C:\Program Files\Sublime Text 3\sublime_text.exe" ProjectSettings/QualitySettings.asset
"C:\Program Files\Sublime Text 3\sublime_text.exe" ProjectSettings/TagManager.asset
"C:\Program Files\Sublime Text 3\sublime_text.exe" ProjectSettings/TimeManager.asset
"C:\Program Files\Sublime Text 3\sublime_text.exe" ProjectSettings/UnityConnectSettings.asset
"C:\Program Files\Sublime Text 3\sublime_text.exe" ProjectSettings/VFXManager.asset
"C:\Program Files\Sublime Text 3\sublime_text.exe" README.md
